FROM debian:8.6

COPY nsswitch.conf /etc

RUN \
    # Glibc
    mkdir -pv /out/lib && \
    mkdir -pv /out/bin && \
    ln -s /lib /out/lib64 && \
    cd /lib/x86_64-linux-gnu && \
    cp libc.so.6 \
       librt.so.1 \
       libnsl.so.1 \
       libm.so.6 \
       libpthread.so.0 \
       libdl.so.2 \
       libnss_compat.so.2 \
       libnss_dns.so.2 \
       libnss_files.so.2 \
       libnss_hesiod.so.2 \
       libnss_nis.so.2 \
       libnss_nisplus.so.2 \
       libresolv.so.2 \
       libBrokenLocale.so.1 \
       libSegFault.so \
       libanl.so.1 \
       libcidn.so.1 \
       libcrypt.so.1 \
       libmemusage.so \
       libthread_db.so.1 \
       libutil.so.1 \
       ld-linux-x86-64.so.2 /out/lib && \

    # Locale
    mkdir -pv /out/usr/lib/locale && \
    cp -r /usr/lib/locale/C.UTF-8 /out/usr/lib/locale && \

    # nsswitch.conf
    mkdir -pv /out/etc && \
    cp /etc/nsswitch.conf /out/etc && \

    cd /out && \
    tar czfv /rootfs.tar.gz ./*